// Mocks generated by Mockito 5.4.6 from annotations
// in so_bicos/test/core/data/repositories/job/job_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result_dart/result_dart.dart' as _i4;
import 'package:so_bicos/core/data/datasources/job/job_category_datasource.dart'
    as _i7;
import 'package:so_bicos/core/data/datasources/job/job_datasource.dart' as _i2;
import 'package:so_bicos/core/external/models/job/job_api_model.dart' as _i5;
import 'package:so_bicos/core/external/models/job/job_category_api_model.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobDataSource extends _i1.Mock implements _i2.JobDataSource {
  @override
  _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>> getAllJobs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllJobs, []),
            returnValue:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(this, Invocation.method(#getAllJobs, [])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(this, Invocation.method(#getAllJobs, [])),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>> getJobsByAuthor(
    String? author,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getJobsByAuthor, [author]),
            returnValue:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(this, Invocation.method(#getJobsByAuthor, [author])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(this, Invocation.method(#getJobsByAuthor, [author])),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>>
  getJobsByCategoryId(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getJobsByCategoryId, [categoryId]),
            returnValue:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(
                    this,
                    Invocation.method(#getJobsByCategoryId, [categoryId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i5.JobApiModel>, Exception>
                  >(
                    this,
                    Invocation.method(#getJobsByCategoryId, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.JobApiModel>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> publishJob(
    _i5.JobApiModel? job,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#publishJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#publishJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#publishJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> updateJob(_i5.JobApiModel? job) =>
      (super.noSuchMethod(
            Invocation.method(#updateJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#updateJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#updateJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> deleteJob(_i5.JobApiModel? job) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#deleteJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#deleteJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);
}

/// A class which mocks [JobCategoryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobCategoryDataSource extends _i1.Mock
    implements _i7.JobCategoryDataSource {
  @override
  _i3.Future<_i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>>
  getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue:
                _i3.Future<
                  _i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>
                  >(this, Invocation.method(#getAllCategories, [])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>
                  >(this, Invocation.method(#getAllCategories, [])),
                ),
          )
          as _i3.Future<
            _i4.ResultDart<List<_i8.JobCategoryApiModel>, Exception>
          >);

  @override
  _i3.Future<_i4.ResultDart<_i8.JobCategoryApiModel, Exception>>
  getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue:
                _i3.Future<
                  _i4.ResultDart<_i8.JobCategoryApiModel, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<_i8.JobCategoryApiModel, Exception>
                  >(this, Invocation.method(#getCategoryById, [id])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.ResultDart<_i8.JobCategoryApiModel, Exception>
                >.value(
                  _i6.dummyValue<
                    _i4.ResultDart<_i8.JobCategoryApiModel, Exception>
                  >(this, Invocation.method(#getCategoryById, [id])),
                ),
          )
          as _i3.Future<_i4.ResultDart<_i8.JobCategoryApiModel, Exception>>);
}
