// Mocks generated by Mockito 5.4.6 from annotations
// in so_bicos/test/ui/home/viewmodels/home_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:result_dart/result_dart.dart' as _i4;
import 'package:so_bicos/core/data/repositories/job/job_repository.dart' as _i2;
import 'package:so_bicos/core/domain/models/job/job.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobRepository].
///
/// See the documentation for Mockito's code generation for more information.
class JobRepositoryMock extends _i1.Mock implements _i2.JobRepository {
  @override
  _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>> getAllJobs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllJobs, []),
            returnValue:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getAllJobs, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getAllJobs, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>> getJobsByAuthor(
    String? author,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getJobsByAuthor, [author]),
            returnValue:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getJobsByAuthor, [author]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getJobsByAuthor, [author]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>> getJobsByCategory(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getJobsByCategory, [categoryId]),
            returnValue:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getJobsByCategory, [categoryId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<List<_i5.Job>, Exception>>(
                    this,
                    Invocation.method(#getJobsByCategory, [categoryId]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<List<_i5.Job>, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> publishJob(_i5.Job? job) =>
      (super.noSuchMethod(
            Invocation.method(#publishJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#publishJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#publishJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> updateJob(_i5.Job? job) =>
      (super.noSuchMethod(
            Invocation.method(#updateJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#updateJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#updateJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);

  @override
  _i3.Future<_i4.ResultDart<void, Exception>> deleteJob(_i5.Job? job) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJob, [job]),
            returnValue: _i3.Future<_i4.ResultDart<void, Exception>>.value(
              _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                this,
                Invocation.method(#deleteJob, [job]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.ResultDart<void, Exception>>.value(
                  _i6.dummyValue<_i4.ResultDart<void, Exception>>(
                    this,
                    Invocation.method(#deleteJob, [job]),
                  ),
                ),
          )
          as _i3.Future<_i4.ResultDart<void, Exception>>);
}
